//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareReleaseMapService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentSystemGroupCode
    {
        public int ID { get; set; }
        public string SystemGroupCode { get; set; }
        public string ComponentGroupCode { get; set; }
    }
}
