//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareReleaseMapService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DialectText
    {
        public int MicrosoftLocaleID { get; set; }
        public int TextID { get; set; }
        public string LanguageText { get; set; }
        public System.DateTime ModificationDateTime { get; set; }
        public string ModifiedbyDatabaseLoginName { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual LanguageDialect LanguageDialect { get; set; }
        public virtual TextReference TextReference { get; set; }
    }
}
