//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareReleaseMapService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseComponent
    {
        public string ComponentGroupCode { get; set; }
        public int ReleaseID { get; set; }
        public string ComponentNumber { get; set; }
        public string ComponentNumberSpecWeek { get; set; }
        public bool ReleaseDerivationIndicator { get; set; }
        public string LastModifiedUserName { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual Release Release { get; set; }
    }
}
