//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareReleaseMapService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseNoteType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReleaseNoteType()
        {
            this.ReleaseNotes = new HashSet<ReleaseNote>();
        }
    
        public string ReleaseNoteTypeCode { get; set; }
        public string ReleaseNoteTypeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseNote> ReleaseNotes { get; set; }
    }
}
