//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareReleaseMapService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseNote
    {
        public int ReleaseID { get; set; }
        public string ReleaseNoteTypeCode { get; set; }
        public int ReleaseNoteTextID { get; set; }
        public string LastModifiedUserName { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual Release Release { get; set; }
        public virtual ReleaseNoteType ReleaseNoteType { get; set; }
        public virtual TextReference TextReference { get; set; }
    }
}
