//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareReleaseMapService.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageDialect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LanguageDialect()
        {
            this.DialectTexts = new HashSet<DialectText>();
        }
    
        public int MicrosoftLocaleID { get; set; }
        public string MicrosoftLocaleDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DialectText> DialectTexts { get; set; }
    }
}
