//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareReleaseMapService.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POCRCEntities1 : DbContext
    {
        public POCRCEntities1()
            : base("name=POCRCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComponentSystemGroupCode> ComponentSystemGroupCodes { get; set; }
        public virtual DbSet<DialectText> DialectTexts { get; set; }
        public virtual DbSet<LanguageDialect> LanguageDialects { get; set; }
        public virtual DbSet<Release> Releases { get; set; }
        public virtual DbSet<ReleaseComponent> ReleaseComponents { get; set; }
        public virtual DbSet<ReleaseNote> ReleaseNotes { get; set; }
        public virtual DbSet<ReleaseNoteType> ReleaseNoteTypes { get; set; }
        public virtual DbSet<ReleaseType> ReleaseTypes { get; set; }
        public virtual DbSet<SystemGroup> SystemGroups { get; set; }
        public virtual DbSet<TextReference> TextReferences { get; set; }
    }
}
