//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareReleaseMapService.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Release()
        {
            this.ReleaseComponents = new HashSet<ReleaseComponent>();
            this.ReleaseNotes = new HashSet<ReleaseNote>();
        }
    
        public int ReleaseID { get; set; }
        public string SystemGroupCode { get; set; }
        public string ReleaseCode { get; set; }
        public Nullable<short> ModelYear { get; set; }
        public string VersionNumber { get; set; }
        public int ReleaseTypeID { get; set; }
        public bool ConnectCapableIndicator { get; set; }
        public string MinimumConnectClientVersion { get; set; }
        public string LastModifiedUserName { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public byte[] timestamp { get; set; }
        public bool ActiveIndicator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseComponent> ReleaseComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseNote> ReleaseNotes { get; set; }
        public virtual ReleaseType ReleaseType { get; set; }
    }
}
